### your site title here

title: Rafael M. Yassue	
description: Data Science | Genetics and Plant Breeding | Phenomics

baseurl: /cv-online #name of GitHub repository
url: #custom url to be used instead of GitHub repository
email: rafael.yassue@usp.br #


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
facebook: rafael.yassue
twitter: RYassue
linkedin: rafael-massahiro-yassue-41941865/
github: RafaelYassue
researchgate: Rafael-Yassue
orcid: 0000-0002-7424-2227

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
